### ISSUE TITLE
Parou de funcionar com o Venom 4

### ISSUE THREAD

**Issue by Sulivan1999** [billbarsch/myzap#122]
Após a atualização do Venom para a versão 4 não é possível mais identificar o status conectado após a leitura do QR-code, também não é possível enviar mensagens.

**Comment by jhowbhz** [comment]
Tem alguma sugestão de update?

**Comment by Sulivan1999** [comment]
> Tem alguma sugestão de update?

Bom, não sei muito bem o que mudou... Porém em meus testes eu identifiquei que o WhatsApp conecta normal após a leitura do qr-code, porém não é possível pegar o status da sessão e nem enviar mensagens chamando sendText, mesmo estando mostrando no celular e no terminal que a sessão está conectado.

**Comment by vsoaresz** [comment]
Mesmo problema pra mim.

**Comment by AlanMartines** [comment]
Faz um teste, dê um
```sh
 npm remove venom-bot
```
e depois um 
```sh
npm install venom-bot@3.1.12
```
para usar a versão sem Multdevice.

**Comment by Maycon355** [comment]
Ainda mesmo erro...

**Comment by mrhewbuc** [comment]
O mesmo aqui

**Comment by mrhewbuc** [comment]
> ```shell
> npm install venom-bot@3.1.12
> ```
Com a sua sugestão, o erro muda.
Error: Evaluation failed: TypeError: Cannot read property 'wid' of undefined
    at Object.window.WAPI.window.WAPI.sendMessage (/root/myzap/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:44715)
    at ExecutionContext._evaluateInternal (/root/myzap/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (/root/myzap/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:106:16)
