### ISSUE TITLE
Server5xxDrop Error

### ISSUE THREAD

**Issue by ykose1982** [billbarsch/myzap#124]
It just occurs today. I didnt make any update or something. It send 2-3 messages then this error occurs

```
Webhook no defined
webhooks status message....
Server5xxDrop
    at new i (https://web.whatsapp.com/bootstrap_qr.6a499aa48d60caaefb11.js:2:452434)
    at new f (https://web.whatsapp.com/bootstrap_qr.6a499aa48d60caaefb11.js:61:24219)
    at Object.on5xx (https://web.whatsapp.com/bootstrap_qr.6a499aa48d60caaefb11.js:56:576420)
    at Object.onMessage (https://web.whatsapp.com/bootstrap_qr.6a499aa48d60caaefb11.js:56:577302)
    at Object._onParsedMsg (https://web.whatsapp.com/bootstrap_qr.6a499aa48d60caaefb11.js:61:18040)
    at Object._onMessage (https://web.whatsapp.com/bootstrap_qr.6a499aa48d60caaefb11.js:61:17646)
cleanup
```

Please help..

**Comment by jhowbhz** [comment]
This is happening to me too sometimes, it seems to be something pm2 related, are you using this package?

**Comment by ykose1982** [comment]
> This is happening to me too sometimes, it seems to be something pm2 related, are you using this package?

Same with run pm2 and node meaning not about the pm2. I've updated the latest but same issue...
