### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'createWid')

### ISSUE THREAD

**Issue by ykose1982** [billbarsch/myzap#125]
## Description

When sending message, getting this error

## Environment

- Latest version of myzap
- Chromium
- Ubuntu 20.18
- Node 16

## Log Output

```
TypeError: Cannot read properties of undefined (reading 'createWid')
    at Object.<anonymous> (/root/myzap/node_modules/@wppconnect-team/wppconnect/dist/lib/wapi/wapi.js:1:110360)
    at Generator.next (<anonymous>)
    at vo (/root/myzap/node_modules/@wppconnect-team/wppconnect/dist/lib/wapi/wapi.js:1:85350)
    at a (/root/myzap/node_modules/@wppconnect-team/wppconnect/dist/lib/wapi/wapi.js:1:85554)
    at /root/myzap/node_modules/@wppconnect-team/wppconnect/dist/lib/wapi/wapi.js:1:85615
    at j (https://web.whatsapp.com/bootstrap_qr.6a499aa48d60caaefb11.js:2:390225)
    at new g (https://web.whatsapp.com/bootstrap_qr.6a499aa48d60caaefb11.js:2:381120)
    at Object.<anonymous> (/root/myzap/node_modules/@wppconnect-team/wppconnect/dist/lib/wapi/wapi.js:1:85494)
    at Object.checkNumberStatus (/root/myzap/node_modules/@wppconnect-team/wppconnect/dist/lib/wapi/wapi.js:1:110591)
    at __puppeteer_evaluation_script__:44:68
```

Any idea?

**Comment by ykose1982** [comment]
I have no idea about the error. Anyone out there?

**Comment by ykose1982** [comment]
I connected from 4G and tested (mobile phone's internet), it works. Very interestingly it doesn't work from my home internet.

**Comment by AlanMartines** [comment]
@ykose1982 testa ai, @edupoli fez os ajustes...
