### ISSUE TITLE
WPPConnect pedindo qrcode toda vez ao iniciar

### ISSUE THREAD

**Issue by djphi** [billbarsch/myzap#164]
Mesmo com a sessão salva no firebase, continua pedindo qrcode toda vez que inicio. Estou errando em alguma coisa?

**Comment by leandrogrupozani** [comment]
Aguardando também

**Comment by djphi** [comment]
mudei o meu whatsapp para whatsapp business e resolveu o problema

**Comment by leandrogrupozani** [comment]
Mas o whatsapp do meu celular é o business

**Comment by djphi** [comment]
um amigo aí deu a opção de adicionar essa linha: 
`puppeteerOptions: { userDataDir: './tokens/' + session, },`
antes de "createPathFileToken: false,"
em engine/WppConnect
faça o teste

**Comment by leandrogrupozani** [comment]
Já fiz este teste também!! 
não deu certo.

Depois vou ver com mais calma o que aparece quando inicio o wppconnect....

**Comment by djphi** [comment]
deleta os arquivos dentro da pasta token, entra no firebase e deleta a sessão. começa do 0

**Comment by leandrogrupozani** [comment]
vou fazer isso

**Comment by leandrogrupozani** [comment]
Nada...


at new RequestError (C:\nodes\myzap\node_modules\request-promise-core\lib\errors.js:14:15)
at Request.plumbing.callback (C:\nodes\myzap\node_modules\request-promise-core\lib\plumbing.js:87:29)
at Request.RP$callback [as _callback] (C:\nodes\myzap\node_modules\request-promise-core\lib\plumbing.js:46:31)
at self.callback (C:\nodes\myzap\node_modules\request\request.js:185:22)
at Request.emit (node:events:526:28)
at Request.init (C:\nodes\myzap\node_modules\request\request.js:458:17)
at Request.RP$initInterceptor [as init] (C:\nodes\myzap\node_modules\request-promise-core\configure\request2.js:45:29)
... 6 lines matching cause stack trace ...
at async Server.<anonymous> (file:///C:/nodes/myzap/index.js:124:22) {
use: Error: Invalid protocol: 191.243.12.206:
  at Request.init (C:\nodes\myzap\node_modules\request\request.js:458:31)
  at Request.RP$initInterceptor [as init] (C:\nodes\myzap\node_modules\request-promise-core\configure\request2.js:45:29)
  at new Request (C:\nodes\myzap\node_modules\request\request.js:127:8)
  at request (C:\nodes\myzap\node_modules\request\index.js:53:10)
  at file:///C:/nodes/myzap/startup.js:72:17
  at Array.map (<anonymous>)
  at startAllSessions (file:///C:/nodes/myzap/startup.js:54:19)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async Server.<anonymous> (file:///C:/nodes/myzap/index.js:124:22),
ror: Error: Invalid protocol: 191.243.12.206:
  at Request.init (C:\nodes\myzap\node_modules\request\request.js:458:31)
  at Request.RP$initInterceptor [as init] (C:\nodes\myzap\node_modules\request-promise-core\configure\request2.js:45:29)
  at new Request (C:\nodes\myzap\node_modules\request\request.js:127:8)
  at request (C:\nodes\myzap\node_modules\request\index.js:53:10)
  at file:///C:/nodes/myzap/startup.js:72:17
  at Array.map (<anonymous>)
  at startAllSessions (file:///C:/nodes/myzap/startup.js:54:19)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async Server.<anonymous> (file:///C:/nodes/myzap/index.js:124:22),

**Comment by leandrogrupozani** [comment]
Vou dar um npm update aqui pra ver o que vira...

**Comment by djphi** [comment]
npm update --force

**Comment by as-schug** [comment]
> deleta os arquivos dentro da pasta token, entra no firebase e deleta a sessão. começa do 0

Pra mim funcionou... Estava há meses com esse problema...
Eu já havia colocado a solução mas nos testes não tive sucesso...
Agora apagando os tokens e zerando os dados do DB, foi perfeito, até o momento... Maiores detalhes no decorrer
Obrigado...

**Comment by wlfonseca** [comment]
Valida as permissões na pasta tokens
