### ISSUE TITLE
Error after scanning QRCode

### ISSUE THREAD

**Issue by ghost** [billbarsch/myzap#18]
After scanning QRCode it says:
```
UnhandledPromiseRejectionWarning: Error: Evaluation failed: ReferenceError: WAPI is not defined
    at eval (eval at waitForPredicatePageFunction (:2:23), <anonymous>:5:29)
    at eval (eval at waitForPredicatePageFunction (:2:23), <anonymous>:6:27)
    at onRaf (__puppeteer_evaluation_script__:49:35)
    at pollRaf (__puppeteer_evaluation_script__:42:15)
    at waitForPredicatePageFunction (__puppeteer_evaluation_script__:7:22)
    at ExecutionContext._evaluateInternal (/root/Workspace/Whatsapp/myzap/myzap/node_modules/puppeteer/lib/ExecutionContext.js:102:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at ExecutionContext.<anonymous> (/root/Workspace/Whatsapp/myzap/myzap/node_modules/puppeteer/lib/helper.js:94:19)
    at WaitTask.rerun (/root/Workspace/Whatsapp/myzap/myzap/node_modules/puppeteer/lib/DOMWorld.js:404:71)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:22829) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:22829) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by jairolima** [comment]
Tô com o mesmo problema

**Comment by luizfeer** [comment]
yarn remove venom-bot
yarn add venom-bot

last version:
"venom-bot": "^2.0.14"
