### ISSUE TITLE
Não loga

### ISSUE THREAD

**Issue by misterxis** [billbarsch/myzap#26]
`- Status da sessão: notLogged
- Session name:  session
(node:52153) UnhandledPromiseRejectionWarning: TypeError: Cannot create property 'status' on string 'session'
    at venom.create (/home/ubuntu/mywhats/sessions.js:169:28)
    at Object.<anonymous> (/home/ubuntu/mywhats/node_modules/venom-bot/dist/controllers/initializer.js:298:25)
    at step (/home/ubuntu/mywhats/node_modules/venom-bot/dist/controllers/initializer.js:44:23)
    at Object.next (/home/ubuntu/mywhats/node_modules/venom-bot/dist/controllers/initializer.js:25:53)
    at fulfilled (/home/ubuntu/mywhats/node_modules/venom-bot/dist/controllers/initializer.js:16:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:52153) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:52153) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
- Nome da sessão: undefined
- Status do sistema: STARTING
- Status da sessão: notLogged`

**Comment by misterxis** [comment]
solved
