### ISSUE TITLE
After upgrade venom-bot

### ISSUE THREAD

**Issue by antoniovalenzuela** [billbarsch/myzap#36]
Please help

First error "WAPI is not defined"

npm update venom-bot

And http://localhost:3333/start?sessionName=session1

qrcode...session1
(node:23872) UnhandledPromiseRejectionWarning: TypeError: session.qrcode.replace is not a function
    at /home/venom/myzap/index.js:45:49
    at Layer.handle [as handle_request] (/home/venom/myzap/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/venom/myzap/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/venom/myzap/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/venom/myzap/node_modules/express/lib/router/layer.js:95:5)
    at /home/venom/myzap/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/venom/myzap/node_modules/express/lib/router/index.js:335:12)
    at next (/home/venom/myzap/node_modules/express/lib/router/index.js:275:10)
    at jsonParser (/home/venom/myzap/node_modules/body-parser/lib/types/json.js:110:7)
    at Layer.handle [as handle_request] (/home/venom/myzap/node_modules/express/lib/router/layer.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:23872) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:23872) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by renanvnunes** [comment]
Comigo está acontecendo a mesma coisa.

**Comment by Advansoftware** [comment]
Foi corrigido esse problema agora!
