### ISSUE TITLE
Error after update venom

### ISSUE THREAD

**Issue by JulioGJr** [billbarsch/myzap#77]
(node:137278) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read property 'createWid' of undefined
    at Object.window.WAPI.window.WAPI.checkNumberStatus (/var/www/html/myzap/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:64760)
    at Object.window.WAPI.window.WAPI.sendExist (/var/www/html/myzap/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:29715)
    at Object.window.WAPI.window.WAPI.sendMessage (/var/www/html/myzap/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:38155)
    at __puppeteer_evaluation_script__:3:57
    at ExecutionContext._evaluateInternal (/var/www/html/myzap/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ExecutionContext.evaluate (/var/www/html/myzap/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:106:16)
(node:137278) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 7)

After update venom

**Comment by ykose1982** [comment]
Same here..
