### ISSUE TITLE
I'm having trouble running myzap...

### ISSUE THREAD

**Issue by fbeux** [billbarsch/myzap#85]
I'm having trouble running myzap...
Tried using AWS VPS, both on Debian and Ubuntu Server.
After doing the correct installation according to the tutorial, when trying to run, it shows the error below:

Error: Cannot find module 'venom-bot'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/myzap/sessions.js:7:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

**Comment by Schmarotzer** [comment]
npm update venom-bot
