### ISSUE TITLE
MyZAP parou de enviar mensagens?

### ISSUE THREAD

**Issue by alanvictorjp** [billbarsch/myzap#95]
Bom dia pessoal, de ontem para hoje não estou conseguindo enviar mensagens, só consigo se... primeiramente o numero(whats) cliente, fizer uma interação(enviar alguma mensagem) para o numero(whats) do MyZAP, e nem sempre funciona.

numero de telefone suprimido para xxxxxxxxxxx, equivale a: 5581987654321

Alguns testes que eu efetuei:
- testado com e sem codigo do pais e digito 9.
- testado a versao 10.x e 16.x do nodejs
- venom-bot atualizado
-  testado em outros aparelhos
-  testado com whatsapp e whatsapp business
-  testado com outro numero
-  criado um container do zero, para excluir a possibilidade de algum arquivo corrompido.
- testado em vps diferentes.

**SEM SUCESSO!**

segue abaixo o erro da instancia do node.
```
#### send msg = { sessionName: 'session1', number: 55xxxxxxxxxxx, text: 'teste' }
Error: Evaluation failed: TypeError: this._find is not a function
    at j._serverQuery (https://web.whatsapp.com/bootstrap_qr.428c60993dba5c1514a3.js:55:334921)
    at j._query (https://web.whatsapp.com/bootstrap_qr.428c60993dba5c1514a3.js:55:334450)
    at j.find (https://web.whatsapp.com/bootstrap_qr.428c60993dba5c1514a3.js:55:332582)
    at Object.window.WAPI.window.WAPI.getChat (/myzap/myzap/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:55806)
    at Object.window.WAPI.window.WAPI.sendExist (/myzap/myzap/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:30002)
    at async Object.window.WAPI.window.WAPI.sendMessage (/myzap/myzap/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:40000)
    at ExecutionContext._evaluateInternal (/myzap/myzap/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (/myzap/myzap/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:106:16)
cleanup
```

**Comment by gustavohcmelo** [comment]
Bom dia a todos!

@alanvictorjp comigo está acontecendo o mesmo problema. Tentei até mesmo realizar envios por outras funções como o SendLinkPreview, mas sem sucesso.

Estou utilizando a versões:
Venom 3.1.2
Npm 6.14
Node 14.7

**Comment by alanvictorjp** [comment]
> Bom dia a todos!
> 
> @alanvictorjp comigo está acontecendo o mesmo problema. Tentei até mesmo realizar envios por outras funções como o SendLinkPreview, mas sem sucesso.
> 
> Estou utilizando a versões:
> Venom 3.1.2
> Npm 6.14
> Node 14.7

Cara, parece que voltou aqui, como está ai?

**Comment by gustavohcmelo** [comment]
Pra mim ainda continua da mesma forma. Tu fez algo diferente?

**Comment by alanvictorjp** [comment]
dia 02/09 saiu um update do venom-bot, não li o changelog, mas talvez tenha sido isso que resolveu.

**Comment by gustavohcmelo** [comment]
@alanvictorjp foi exatamente isso. Já tinha realizado um update, mas não havia percebido a informação de que meu npm estava com uma versão não suportada para atualizar o chromium. Atualizei o node para a versão 12 e atualizei o Venom. Tudo certo agora!!

Valeu meu amigo!!
