### ISSUE TITLE
HOST ON HEROKU

### ISSUE THREAD

**Issue by Yash998** [billbarsch/myzap#99]
(node:4) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["secret-key"]
2021-09-14T19:35:39.686379+00:00 app[web.1]:     at ClientRequest.setHeader (_http_outgoing.js:564:3)
2021-09-14T19:35:39.686379+00:00 app[web.1]:     at new ClientRequest (_http_client.js:262:14)
2021-09-14T19:35:39.686380+00:00 app[web.1]:     at Object.request (https.js:374:10)
2021-09-14T19:35:39.686380+00:00 app[web.1]:     at RedirectableRequest._performRequest (/app/node_modules/follow-redirects/index.js:241:24)
2021-09-14T19:35:39.686381+00:00 app[web.1]:     at new RedirectableRequest (/app/node_modules/follow-redirects/index.js:60:8)
2021-09-14T19:35:39.686381+00:00 app[web.1]:     at Object.request (/app/node_modules/follow-redirects/index.js:437:14)
2021-09-14T19:35:39.686382+00:00 app[web.1]:     at dispatchHttpRequest (/app/node_modules/axios/lib/adapters/http.js:195:25)
2021-09-14T19:35:39.686382+00:00 app[web.1]:     at new Promise (<anonymous>)
2021-09-14T19:35:39.686382+00:00 app[web.1]:     at httpAdapter (/app/node_modules/axios/lib/adapters/http.js:46:10)
2021-09-14T19:35:39.686383+00:00 app[web.1]:     at dispatchRequest (/app/node_modules/axios/lib/core/dispatchRequest.js:52:10)

**Comment by jhowbhz** [comment]
Você conseguiu instalar todas as dependências do projeto?
